version: "3"
services:

  api:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ./server:/app/server
      - ./scripts:/app/scripts
    entrypoint: "./node_modules/.bin/nodemon"

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha
