version: "3"
services:

  pay:
    build: .
    image: jsndev/api
    container_name: api 
    links:
      - db
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ./server:/app/server
      - ./scripts:/app/scripts
    entrypoint: "./node_modules/.bin/nodemon"

  db:
    image: mysql
    container_name: mysql_pay
    environment:
      - MYSQL_DATABASE=pay_allfood
      - MYSQL_USER=api
      - MYSQL_PASSWORD=fXd7hdvo
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: front_pay   
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: api
      MYSQL_PASSWORD: fXd7hdvo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "80:80"
    links:
      # for mysql container
      - "db:db" 